name: digplantgrow
favicon: null
layout_spectrum: 0.24745
typography_spectrum: 0.39015
title: Dig Plant Grow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73098282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e7ac2e'
    - '#12351f'
    - '#837783'
    - '#7c3776'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
