name: digplantgrow
favicon: null
layout_spectrum: 0.24745
typography_spectrum: 0.39015
title: Dig Plant Grow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73098282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#532a33'
    - '#d9dad4'
    - '#467b2b'
    - '#83b453'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
