name: digplantgrow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52683
title: Dig Plant Grow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73098282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5625
  lightness: 0.6590214290190488
  saturation: 0.5
  rhythmicContrast: 0.7907578370068222
purpose: []
