name: digplantgrow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52683
title: Dig Plant Grow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73098282-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#532a33'
    - '#d9dad4'
    - '#467b2b'
    - '#83b453'
  brandStrength: 0.625
  lightness: 0.6590214290190488
  saturation: 0.5
  rhythmicContrast: 0.7907578370068222
purpose: []
